# Generated by Django 3.1.6 on 2021-02-23 04:40

from django.db import migrations, models
import django.db.models.deletion
import garden.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WateringStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture_threshold', models.IntegerField(default=garden.models._default_moisture_threshold)),
                ('watering_duration', models.DurationField(default=garden.models._default_watering_duration)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watering_stations', to='garden.garden')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
