# Generated by Django 3.1.6 on 2021-03-03 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import garden.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default=garden.models._default_garden_image, upload_to='')),
                ('is_connected', models.BooleanField(default=garden.models._default_is_connected)),
                ('last_connection_ip', models.GenericIPAddressField(null=True)),
                ('last_connection_time', models.DateTimeField(null=True)),
                ('update_frequency', models.DurationField(default=garden.models._default_update_frequency)),
                ('water_level', models.CharField(choices=[('ok', 'Ok'), ('lo', 'Low')], max_length=2, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='gardens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WateringStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture_threshold', models.IntegerField(default=garden.models._default_moisture_threshold)),
                ('watering_duration', models.DurationField(default=garden.models._default_watering_duration)),
                ('plant_type', models.CharField(blank=True, max_length=255)),
                ('status', models.BooleanField(default=garden.models._default_status)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='watering_stations', to='garden.garden')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WateringStationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture_level', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('watering_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                       related_name='records', to='garden.wateringstation')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
