# Generated by Django 3.1.6 on 2021-03-03 23:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('garden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='garden.garden')),
            ],
        ),
    ]
