# Generated by Django 3.1.6 on 2021-02-23 07:15

from django.db import migrations, models
import garden.models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='name',
            field=models.CharField(default=garden.models._default_garden_name, max_length=255),
        ),
    ]
