# Generated by Django 3.1.6 on 2021-02-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_garden_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateringstation',
            name='plant_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
