# Generated by Django 3.1.6 on 2021-03-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateringstation',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
