# Generated by Django 3.1.6 on 2021-02-25 09:01

from django.db import migrations, models
import garden.models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_wateringstation_plant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='is_connected',
            field=models.BooleanField(default=garden.models._default_is_connected),
        ),
    ]
