# Generated by Django 3.1.6 on 2021-03-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_wateringstation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wateringstation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
