# Generated by Django 3.1.6 on 2021-02-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_garden_is_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='last_connection_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
