# Generated by Django 3.1.6 on 2021-03-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_auto_20210304_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='connection_strength',
            field=models.SmallIntegerField(null=True),
        ),
    ]
