# Generated by Django 3.1.6 on 2021-03-15 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_garden_connection_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='uuid',
            field=models.CharField(max_length=128),
        ),
    ]
