# Generated by Django 3.1.6 on 2021-02-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_garden_last_connection_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='last_connection_time',
            field=models.DateTimeField(null=True),
        ),
    ]
