# Generated by Django 3.1.6 on 2021-03-15 22:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_auto_20210315_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wateringstation',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='wateringstation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
