# Generated by Django 3.1.6 on 2021-02-25 21:39

from django.db import migrations, models
import garden.models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0007_garden_update_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='num_missed_updates',
            field=models.PositiveIntegerField(default=garden.models._default_num_missed_updates),
        ),
    ]
