# Generated by Django 3.1.6 on 2021-02-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0008_garden_num_missed_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='water_level',
            field=models.CharField(choices=[('ok', 'Ok'), ('lo', 'Low')], max_length=2, null=True),
        ),
    ]
