# Generated by Django 3.1.6 on 2021-02-26 00:17

from django.db import migrations, models
import garden.models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0009_garden_water_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateringstation',
            name='status',
            field=models.BooleanField(default=garden.models._default_status),
        ),
    ]
