# Generated by Django 3.1.6 on 2021-02-27 23:24

from django.db import migrations, models
import garden.models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0010_wateringstation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='image',
            field=models.ImageField(default=garden.models._default_garden_image, upload_to=''),
        ),
    ]
