# Generated by Django 3.1.6 on 2021-03-01 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0011_garden_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WateringStationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture_level', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('watering_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='garden.wateringstation')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
