# Generated by Django 3.1.6 on 2021-02-05 01:53

from django.db import migrations, models
import microcontroller.models


class Migration(migrations.Migration):

    dependencies = [
        ('microcontroller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateringstation',
            name='moisture_threshold',
            field=models.IntegerField(default=microcontroller.models._default_moisture_threshold),
        ),
        migrations.AddField(
            model_name='wateringstation',
            name='watering_duration',
            field=models.DurationField(default=microcontroller.models._default_watering_duration),
        ),
    ]
