name: Integrate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - '*'

jobs:
  cpp:
    runs-on: macos-10.15
    steps:
        - uses: actions/checkout@v2
        - uses: lukka/get-cmake@latest

        - name: Install vcpkg
          uses: lukka/run-vcpkg@v6
          with:
            setupOnly: true
            vcpkgGitCommitId: 28c588e6a

        - name: Configure project
          run: |
            cd cpp/Autogarden && \
            cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake

        - name: Build and test
          run: |
            make test-cpp

  python:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1.0.1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install firefox
        run: sudo apt install firefox

      - name: Install geckodriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
          tar -xvzf geckodriver*
          sudo mv geckodriver /usr/local/bin
          geckodriver --version

      - name: Install dependencies
        run: make install

      - name: Unit tests
        run: make test-u

      - name: Integration tests
        run: make test-i

      - name: Functional tests
        run: make test-f

